# -*- coding: utf-8 -*-
"""DSA0401.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0tdT5vCWBae1f0XJApRMBGvOFZEzrGJ

1. Scenario: You are working on a project that involves analyzing student performance data for a
class of 32 students. The data is stored in a NumPy array named student_scores, where each row
represents a student and each column represents a different subject. The subjects are arranged in the
following order: Math, Science, English, and History. Your task is to calculate the average score for
each subject and identify the subject with the highest average score.
Question: How would you use NumPy arrays to calculate the average score for each subject and
determine the subject with the highest average score? Assume 4x4 matrix that stores marks of each
student in given order.
"""

import numpy as np
import matplotlib.pyplot as plt
student_scores = np.array([
    [85, 90, 78, 88],
    [76, 85, 80, 79],
    [92, 88, 84, 91],
    [80, 82, 86, 87]
])
subjects = ["Math", "Science", "English", "History"]
average_scores = np.mean(student_scores, axis=0)
print("Average Scores:")
for subject, avg in zip(subjects, average_scores):
    print(f"{subject}: {avg:.2f}")
highest_avg_index = np.argmax(average_scores);
print("\nSubject with Highest Average Score:")
print(subjects[highest_avg_index], "-", average_scores[highest_avg_index])
plt.figure(figsize=(6,4))
plt.bar(subjects, average_scores)
plt.title("Average Marks of Each Subject")
plt.xlabel("Subjects")
plt.ylabel("Average Marks")
plt.ylim(0, 100);
for i, avg in enumerate(average_scores):
    plt.text(i, avg + 1, f"{avg:.2f}", ha='center')

plt.show()

"""2. Scenario: You are a data analyst working for a company that sells products online. You have been
tasked with analyzing the sales data for the past month. The data is stored in a NumPy array.
Question: How would you find the average price of all the products sold in the past month? Assume
3x3 matrix with each row representing the sales for a different product
"""

import numpy as np
import matplotlib.pyplot as plt

# 3x3 matrix (Rows = Products, Columns = Sales Prices)
sales_data = np.array([
    [100, 120, 110],
    [150, 160, 170],
    [200, 210, 220]
])

# Product names
products = ["Product A", "Product B", "Product C"]

# Average price of each product (row-wise)
average_prices = np.mean(sales_data, axis=1)

# Average price of all products
overall_average = np.mean(sales_data)

print("Average Price of Each Product:")
for product, avg in zip(products, average_prices):
    print(f"{product}: {avg:.2f}")

print("\nOverall Average Price:", overall_average)

# Plot Bar Graph
plt.figure(figsize=(6,4))
plt.bar(products, average_prices)
plt.title("Average Price of Each Product")
plt.xlabel("Products")
plt.ylabel("Average Price")

# Display values on bars
for i, avg in enumerate(average_prices):
    plt.text(i, avg + 2, f"{avg:.2f}", ha='center')

plt.show()

"""3. Scenario: You are working on a project that involves analyzing a dataset containing information
about houses in a neighborhood. The dataset is stored in a CSV file, and you have imported it into a
NumPy array named house_data. Each row of the array represents a house, and the columns contain
various features such as the number of bedrooms, square footage, and sale price.
Question: Using NumPy arrays and operations, how would you find the average sale price of houses
with more than four bedrooms in the neighborhood?
"""

import numpy as np

house_data = np.array([
    [3, 1500, 250000],
    [5, 2200, 450000],
    [4, 1800, 320000],
    [6, 3000, 600000],
    [5, 2500, 500000]
])

houses_more_than_4 = house_data[house_data[:, 0] > 4]

average_price = np.mean(houses_more_than_4[:, 2])

print("Houses with More Than 4 Bedrooms:")
print(houses_more_than_4)

print("\nAverage Sale Price:", average_price)
import matplotlib.pyplot as plt

sale_prices = houses_more_than_4[:, 2]
house_labels = ["House 1", "House 2", "House 3"]

plt.figure(figsize=(6,4))
plt.bar(house_labels, sale_prices)

plt.title("Sale Prices of Houses with More Than 4 Bedrooms")
plt.xlabel("Houses")
plt.ylabel("Sale Price ($)")

for i, price in enumerate(sale_prices):
    plt.text(i, price + 5000, str(price), ha='center')

plt.show()

"""4. Scenario: You are working on a project that involves analyzing the sales performance of a company
over the past four quarters. The quarterly sales data is stored in a NumPy array named sales_data,
where each element represents the sales amount for a specific quarter. Your task is to calculate the
total sales for the year and determine the percentage increase in sales from the first quarter to the fourth
quarter.
Question: Using NumPy arrays and arithmetic operations calculate the total sales for the year and
determine the percentage increase in sales from the first quarter to the fourth quarter?
"""

import numpy as np
import matplotlib.pyplot as plt

# Quarterly sales data
sales_data = np.array([50000, 65000, 70000, 90000])

# Total sales
total_sales = np.sum(sales_data)

# Percentage increase from Q1 to Q4
percentage_increase = ((sales_data[3] - sales_data[0]) / sales_data[0]) * 100

# Print results
print("Total Sales:", total_sales)
print("Percentage Increase:", percentage_increase, "%")

# Plot the graph
quarters = ["Q1", "Q2", "Q3", "Q4"]

plt.plot(quarters, sales_data, marker='o')
plt.title("Quarterly Sales Performance")
plt.xlabel("Quarters")
plt.ylabel("Sales Amount")
plt.grid(True)
plt.show()

"""5. Scenario: You are a data analyst working for a car manufacturing company. As part of your analysis,
you have a dataset containing information about the fuel efficiency of different car models. The dataset
is stored in a NumPy array named fuel_efficiency, where each element represents the fuel efficiency
(in miles per gallon) of a specific car model. Your task is to calculate the average fuel efficiency and
determine the percentage improvement in fuel efficiency between two car models.
Question: How would you use NumPy arrays and arithmetic operations to calculate the average fuel
efficiency and determine the percentage improvement in fuel efficiency between two car models?
"""

import numpy as np
import matplotlib.pyplot as plt

# Fuel efficiency of different car models (MPG)
fuel_efficiency = np.array([20, 25, 30, 35])

# Calculate average fuel efficiency
average_efficiency = np.mean(fuel_efficiency)

# Calculate percentage improvement from Model 1 to Model 4
percentage_improvement = ((fuel_efficiency[3] - fuel_efficiency[0]) / fuel_efficiency[0]) * 100

# Display results
print("Fuel Efficiency:", fuel_efficiency)
print("Average Fuel Efficiency:", average_efficiency, "MPG")
print("Percentage Improvement:", percentage_improvement, "%")

# Plot the graph
models = ["Model 1", "Model 2", "Model 3", "Model 4"]

plt.plot(models, fuel_efficiency, marker='o')
plt.title("Fuel Efficiency of Car Models")
plt.xlabel("Car Models")
plt.ylabel("Fuel Efficiency (MPG)")
plt.grid(True)
plt.show()

"""6. Scenario: You are a cashier at a grocery store and need to calculate the total cost of a customer's
purchase, including applicable discounts and taxes. You have the item prices and quantities in separate
lists, and the discount and tax rates are given as percentages. Your task is to calculate the total cost for
the customer.
Question: Use arithmetic operations to calculate the total cost of a customer's purchase, including
discounts and taxes, given the item prices, quantities, discount rate, and tax rate?
"""

# Item prices
prices = [50, 100, 200]

# Quantities of each item
quantities = [2, 3, 1]

# Discount and Tax rates
discount_rate = 10    # 10%
tax_rate = 5          # 5%

# Calculate subtotal
subtotal = 0
for i in range(len(prices)):
    subtotal += prices[i] * quantities[i]

# Calculate discount
discount = subtotal * discount_rate / 100

# Amount after discount
amount_after_discount = subtotal - discount

# Calculate tax
tax = amount_after_discount * tax_rate / 100

# Final total cost
total_cost = amount_after_discount + tax

# Display results
print("Subtotal:", subtotal)
print("Discount:", discount)
print("Tax:", tax)
print("Total Cost:", total_cost)