# -*- coding: utf-8 -*-
"""FDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLS5zhpu7PjMqKI8rrjwxySzXKxfvdUD

7. Scenario: You are working as a data analyst for an e-commerce company. You have been given a
dataset containing information about customer orders, stored in a Pandas DataFrame named
order_data. The DataFrame has columns for customer ID, order date, product name, and order quantity.
Your task is to analyze the data and answer specific questions about the orders.
Question: Using Pandas DataFrame operations, how would you find the following information from
the order_data DataFrame:
"""

import pandas as pd

order_data = pd.DataFrame({
    'Customer_ID': [101, 102, 101, 103, 102, 101],
    'Order_Date': ['2024-01-10', '2024-01-12', '2024-01-15',
                   '2024-01-18', '2024-01-20', '2024-01-25'],
    'Product_Name': ['Laptop', 'Mouse', 'Laptop', 'Keyboard', 'Mouse', 'Monitor'],
    'Order_Quantity': [1, 2, 1, 3, 1, 2]
})

order_data['Order_Date'] = pd.to_datetime(order_data['Order_Date'])

orders_per_customer = order_data.groupby('Customer_ID').size()
print("Orders per Customer:")
print(orders_per_customer)

avg_quantity = order_data.groupby('Product_Name')['Order_Quantity'].mean()
print("\nAverage Order Quantity:")
print(avg_quantity)

earliest_date = order_data['Order_Date'].min()
latest_date = order_data['Order_Date'].max()

print("\nEarliest Order Date:", earliest_date)
print("Latest Order Date:", latest_date)

"""8.Top 5 Most Sold Products"""

import pandas as pd

# Sample sales DataFrame
sales_data = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Keyboard',
                    'Mouse', 'Monitor', 'Laptop', 'Mouse'],
    'Quantity': [5, 10, 3, 4, 7, 2, 6, 8]
})

# Top 5 products sold the most
top_products = sales_data.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(5)

print("Top 5 Products Sold:")
print(top_products)

"""9. Property Data Analysis"""

import pandas as pd

# Sample property DataFrame
property_data = pd.DataFrame({
    'Property_ID': [1, 2, 3, 4, 5],
    'Location': ['Chennai', 'Hyderabad', 'Chennai', 'Bangalore', 'Hyderabad'],
    'Bedrooms': [3, 5, 4, 2, 6],
    'Area_sqft': [1200, 2500, 1800, 1000, 3000],
    'Listing_Price': [6000000, 9000000, 7500000, 5000000, 12000000]
})

# 1. Average listing price in each location
avg_price = property_data.groupby('Location')['Listing_Price'].mean()

print("Average Listing Price:")
print(avg_price)

# 2. Number of properties with more than four bedrooms
more_than_4 = property_data[property_data['Bedrooms'] > 4].shape[0]

print("\nProperties with more than 4 bedrooms:", more_than_4)

# 3. Property with the largest area
largest_property = property_data.loc[property_data['Area_sqft'].idxmax()]

print("\nProperty with Largest Area:")
print(largest_property)

"""10. Scenario: You are working on a data visualization project and need to create basic plots using
Matplotlib. You have a dataset containing the monthly sales data for a company, including the month
and corresponding sales values. Your task is to develop a Python program that generates line plots and
bar plots to visualize the sales data.
Question:
1: How would you develop a Python program to create a line plot of the monthly sales data?
2: How would you develop a Python program to create a bar plot of the monthly sales data?
"""

import matplotlib.pyplot as plt

# Sample dataset
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
          sales = [120, 150, 170, 130, 160, 180,
                   200, 210, 190, 220, 230, 250]

                   # Create subplots: 1 row, 2 columns
                   fig, axs = plt.subplots(1, 2, figsize=(12, 5))

                   # --- Line Plot ---
                   axs[0].plot(months, sales, marker='o', linestyle='-', color='b')
                   axs[0].set_title("Monthly Sales - Line Plot")
                   axs[0].set_xlabel("Months")
                   axs[0].set_ylabel("Sales")
                   axs[0].grid(True)

                   # --- Bar Plot ---
                   axs[1].bar(months, sales, color='orange')
                   axs[1].set_title("Monthly Sales - Bar Plot")
                   axs[1].set_xlabel("Months")
                   axs[1].set_ylabel("Sales")

                   # Adjust layout for better spacing
                   plt.tight_layout()

                   # Show both plots
                   plt.show()